;; Emacs keys

(evil-define-key 'normal neotree-mode-map (kbd "h") 'neotree-hide)
(evil-define-key 'normal neotree-mode-map (kbd "j") 'neotree-next-line)
(evil-define-key 'normal neotree-mode-map (kbd "k") 'neotree-previous-line)
(evil-define-key 'normal neotree-mode-map (kbd "l") 'neotree-enter)

(define-key evil-normal-state-map (kbd "<SPC>") 'evil-end-of-line)
(define-key evil-visual-state-map (kbd "<SPC>") 'evil-end-of-line)
; For specific mode use: (evil-define-key 'insert mode-map key def)

(evil-leader/set-leader ",")
(evil-leader/set-key "t f" 'neotree-toggle)
(evil-leader/set-key "t r" 'linum-relative-mode)
(evil-leader/set-key "f e d" 'open-emacs-file)
(evil-leader/set-key "e e" 'eval-last-sexp)
(evil-leader/set-key "w 1" 'winum-select-window-1)
(evil-leader/set-key "w 2" 'winum-select-window-2)
(evil-leader/set-key "w 3" 'winum-select-window-3)
(evil-leader/set-key "w 4" 'winum-select-window-4)
(evil-leader/set-key "w 5" 'winum-select-window-5)
(evil-leader/set-key "w 6" 'winum-select-window-6)
(evil-leader/set-key "w h" 'evil-window-left)
(evil-leader/set-key "w k" 'evil-window-up)
(evil-leader/set-key "w j" 'evil-window-down)
(evil-leader/set-key "w l" 'evil-window-right)
(evil-leader/set-key "w -" 'delete-other-windows)
(evil-leader/set-key "w o" 'other-window)
(evil-leader/set-key "t n" 'linum-mode)
